### ISSUE TITLE
Upgrade to Jetty 9 (prior versions are now EOL)

### ISSUE THREAD

**Issue by joakime** [ring-clojure/ring#183]
At the end of 2014, prior versions of Jetty, Jetty 7 and Jetty 8 were EOL'd (End of Life).

https://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00069.html

No further work with Jetty 7 and Jetty 8 will be performed.
Upgrade to Jetty 9 for all current work and security fixes. (this includes the ever changing world of SSL/TLS and the upcoming impact of http2 to browser behavior)

Also note, prior claims that Ring cannot move to Java 7 yet should be reevaluated, as in fact even Java 7 will be EOL in April 2015.

http://www.oracle.com/technetwork/java/eol-135779.html

If you haven't upgraded Java yet, you should consider doing so this year.

**Comment by michaelklishin** [comment]
Discussed a million times before. Ring wants to keep JDK 6 compatibility for now.

**Comment by michaelklishin** [comment]
Also, there is a [Jetty 9 Ring adapter](https://github.com/sunng87/ring-jetty9-adapter).

**Comment by weavejester** [comment]
Thanks for bringing this to my attention, @joakime. If Jetty 7 support is coming to a close, we should consider moving to a later version, however, from the announcement they indicate they still have corporate clients on Jetty 7, and that any serious security issues will still be addressed, so there is some leeway.

In the past I've avoided moving Ring to Jetty 9 because of its dependency on Java 1.7. According to [The State of Clojure 2014](https://cognitect.wufoo.com/reports/state-of-clojure-2014-results/), 13.89% of people still target Java 1.6. Unfortunately, it looks like we may be forced to choose the least problematic option and upgrade the Jetty adapter. People stuck with older versions will still have the option of using Ring with other adapters.

**Comment by joakime** [comment]
WebTide, the group that maintains Jetty for corporate clients, can build security fixes in for those clients.

However, there has yet to be such a need in the past 20 years of Jetty (yes, 2015 marks 20 years of Jetty).

Disclosure: I am a committer on Jetty and also work for WebTide. (and the one that wrote that jetty-announce email about the EOL)

**Comment by jmcc0nn3ll** [comment]
Just to reinforce what @joakime is saying....  I am the Product Manager for Webtide and a long time Jetty committer as well. While professional support will be available for Jetty 7 and 8 (shoot, even Jetty 6) for the foreseeable future, the likelihood of another release of 7 or 8 addressing anything but a catastrophic  security issue is highly unlikely.  That being said, if anyone has concerns or needs for support on these versions they are welcome to ping us.

**Comment by mumrah** [comment]
Even upgrading to Jetty 8 (which keeps Java 1.6) would be an improvement as this brings compatibility for the Servlet 3.0 API (according to https://wiki.eclipse.org/Jetty/Starting/Jetty_Version_Comparison_Table)

**Comment by owenludong** [comment]
Is there an upgrade document from jetty8 to 9?

**Comment by weavejester** [comment]
There's no change to the API as part of the Jetty changes, @owenludong.
