### ISSUE TITLE
Query parameters should be US-ASCII encoded, always

### ISSUE THREAD

**Issue by malcolmsparks** [ring-clojure/ring#212]
`params-request` appears to allow the charset in the Content-Type header to dictate the charset used when decoding the URI's query-string. 

This is wrong. The Content-Type only applies to the request body, the URI is always US-ASCII, with additional percent encodings as necessary. See https://tools.ietf.org/html/rfc3986#section-2.4

```clojure
(defn params-request
  "Adds parameters from the query string and the request body to the request
  map. See: wrap-params."
  {:arglists '([request] [request options])
   :added "1.2"}
  [request & [opts]]
  (let [encoding (or (:encoding opts)
                     (req/character-encoding request)
                     "UTF-8")
        request  (if (:form-params request)
                   request
                   (assoc-form-params request encoding))]
    (if (:query-params request)
      request
      (assoc-query-params request encoding))))
```

**Comment by malcolmsparks** [comment]
I think this is not a simple issue, closing.

http://stackoverflow.com/questions/140549/what-character-set-should-i-assume-the-encoded-characters-in-a-url-to-be-in

**Comment by malcolmsparks** [comment]
Very useful link

http://www.w3.org/TR/html5/forms.html#application/x-www-form-urlencoded-encoding-algorithm

**Comment by weavejester** [comment]
The character encoding refers to the characters decoded from percent-encoded values, rather than the character encoding of the query string itself.

However, whether it should use the request character by default may be the wrong approach. The guidelines say that it should assume the character encoding of the response used to serve the form, which isn't necessarily information that the middleware has available to it, hence the reason Ring tries to use the request content-type as a fallback. But perhaps a better approach would be to just default to UTF-8.
