### ISSUE TITLE
ring.middleware.keyword-params/keyword-syntax? not keywordising words starting with numbers

### ISSUE THREAD

**Issue by sirobinson** [ring-clojure/ring#237]
```clojure
(defn- keyword-syntax? [s]
  (re-matches #"[A-Za-z*+!_?-][A-Za-z0-9*+!_?-]*" s))
```

What is the reason for not allowing numbers in the first character being checked?
AFAIK there's no clojure convention preventing numbers from being the first character of a keyword?

Am working with a bunch of size->url json constructs

```
{"50x50": "url....",
 "100x100": "url...",
etc}
```

Why not

```clojure
(defn- keyword-syntax? [s]
  (re-matches #"[A-Za-z0-9*+!_?-]*" s))
```

?

Could it break something downstream?

Thanks

**Comment by sirobinson** [comment]
Damn you markdown!
Basically, regex is
"[A-Za-z*+!_?-][A-Za-z0-9*+!_?-]*"
But wondering why it can't be 
"[A-Za-z0-9*+!_?-]*"

**Comment by weavejester** [comment]
Because a keyword or symbol can't begin with a number. To quote the [Clojure reader docs](http://clojure.org/reader):

> Symbols begin with a non-numeric character and can contain alphanumeric characters and *, +, !, -, _, ', and ? (other characters may be allowed eventually).

> Keywords are like symbols, except: They can and must begin with a colon, e.g. :fred

**Comment by sirobinson** [comment]
Thanks :)

Sent from my Windows Phone
________________________________

**Comment by peter** [comment]
I also need to convert string keys starting with digits to keywords. I see what the documentation is saying but as far as I can tell keywords starting with digits still work fine in clojure, i.e.:

app.system=> (type :3d)
clojure.lang.Keyword
app.system=> (:3d {:3d "foobar"})
"foobar"
app.system=> (get {:3d "foobar"} :3d)
"foobar"

Is there any problem with using such keywords that I am not seeing here?

**Comment by weavejester** [comment]
The Clojure compiler currently allows a lot of things that the reader documentation doesn't. It's better to go with the reader docs rather than relying on undocumented functionality in the compiler that might go away in future versions.

That said, the docs are ambiguous whether `:3d` is a valid keyword or not.

**Comment by peter** [comment]
I think the confusion here is around what is a valid keyword literal and what is a valid non-literal keyword. I don't see why the middleware should be constrained by literal syntax. As far as I can tell any string can be converted to a keyword. I think more developers will be bitten by this. In my case it's inconsisten with what the monger library does. I assume it's the same with Cheshire and Clojure.walk but I haven't checked. Equality checks break down when key types are not consistent.

I doubt that Rich will constrain the ability to convert strings to keywords. If nothing else this would be a major backwards incompatibility.

**Comment by peter** [comment]
(clojure.walk/keywordize-keys {"123 foo bar" 1})
=> {:123 foo bar 1}

(require '[cheshire.core :as json])
(json/parse-string "{\"123 foo bar\": 1}" true)
=> {:123 foo bar 1}

**Comment by weavejester** [comment]
It's true that the `keyword` function doesn't check its input, but I suspect that's more for performance reasons, rather than an attempt to separate "literal keywords" and "non-literal keywords". If such a thing was intended, I expect it would have been mentioned in the documentation.

Once the core functions of Clojure are specced, my guess is that the `keyword` function will gain additional validation checks once it has been instrumented. I don't view this as a major backwards incompatibility, because the docs are clear about what valid keywords are and what they are not.

The `keyword` and `keywordize-keys` functions do not necessarily work on external input, so we don't necessarily need to sanitise the input every time. On the other hand, the `wrap-keyword-params` middleware does work with external input, which is why it santises the keywords before presenting them to the user.

**Comment by weavejester** [comment]
[CLJ-17](http://dev.clojure.org/jira/browse/CLJ-17) confirms my intuition:

> Runtime validation off the table for perf reasons.

There are suggestions for reader syntax that would allow keywords and symbols with arbitrary characters, but as that's not in Clojure, I think we need to assume that if a keyword or symbol isn't valid to read, it's not valid at all.

**Comment by weavejester** [comment]
In addition, [CLJ-1252](http://dev.clojure.org/jira/browse/CLJ-1252) seems to suggest that the keyword `:3d` was not intended to be valid.

**Comment by peter** [comment]
There is at least one case where keywordizing all strings can get you into trouble and that is with strings containing slashes, i.e.:

(name (keyword "foo/bar"))
=> "bar"

(name (keyword "/foo/bar"))
=> "foo/bar"

I was planning on keywordizing all strings across the board but given the problem with slashes I think I will use the restrictive approach of your middleware. The third option would be to use string keys across the board but I'm not happy about that either. With the partial approach I just have to make sure that the exact same keywordize strategy is used across my codebase for equality comparisons to work, in particular with data from Mongodb. I think I can achieve this by passing :keywordize-fields false to Monger and then keywordizing manually.

The overall problem here though is that the keywordize strategy should be consistent across libraries.
