### ISSUE TITLE
Consider providing a formal spec for the spec :)

### ISSUE THREAD

**Issue by ddossot** [ring-clojure/ring#247]
In case there's any interest for it, I went through the exercise of capturing the current spec with clj.spec...

```clojure
(ns XXX
  (:require [clojure.spec :as s])
  (:import  [java.io File InputStream]
            [java.security.cert X509Certificate]))

;;
;; Ring Spec 1.3 ( https://github.com/ring-clojure/ring/blob/1.5.0/SPEC )
;;
(s/def ::server-port int?)
(s/def ::server-name string?)
(s/def ::remote-addr string?)
(s/def ::uri string?)
(s/def ::scheme keyword?)
(s/def ::request-method keyword?)
(s/def ::protocol string?)
(s/def ::headers map?)
(s/def ::query-string string?)
(s/def ::content-type string?)
(s/def ::content-length int?)
(s/def ::character-encoding string?)
(s/def ::ssl-client-cert #(instance? X509Certificate %))
(s/def ::req-body #(instance? InputStream %))
(s/def ::status int?)
(s/def ::res-body (s/or :string string?
                        :seq seq?
                        :file #(instance? File %)
                        :stream #(instance? InputStream %)))

(s/def ::request
  (s/keys :req-un [::server-port
                   ::server-name
                   ::remote-addr
                   ::uri
                   ::scheme
                   ::request-method
                   ::protocol
                   ::headers]
           :opt-un[::query-string
                   ::content-type
                   ::content-length
                   ::character-encoding
                   ::ssl-client-cert
                   ::req-body]))

(s/def ::response
  (s/keys :req-un [::status
                   ::headers]
          :opt-un [::res-body]))
```

**Comment by weavejester** [comment]
Thanks, but it looks like there are some errors in the spec you provide. Wouldn't `::req-body` be translated to `:req-body` rather than `:body`?

**Comment by ddossot** [comment]
Yes, you're right, I've tested request before implementing response, and wrecked it in the process.

Agreed on better names and stricter rules.

**Comment by alexanderkiel** [comment]
Why is this issue closed? I would like to have a spec for ring.

One problem, I see regarding `:body` is that the request body differs from the response body. While the request body can be only an `InputStream`, the response body can be also a string and others. We could solve this problem by using different namespaces for the request and response body keywords.

**Comment by ddossot** [comment]
I closed it out of shame of my poor lazy Saturday morning hack of a job 😅 Since there's interest, I re-open it and maybe we can salvage this stem of spec and make it better 👍

**Comment by alexanderkiel** [comment]
Thanks for opening the issue again @ddossot. Currently I have the following: https://gist.github.com/alexanderkiel/a1b583741008aa346733a85bda074725

**Comment by plexus** [comment]
Commenting here because gists don't cause notifications. I'm a big fan of this initiative, having built-in specs for ring adapters and middleware would detect a lot of bugs.

Re. `:request-method`, I see two approaches

- include all methods defined in some RFC or RFC draft, e.g. https://annevankesteren.nl/2007/10/http-methods
If you're coming up with your own stuff you're obviously on your own. This list may grow in the future, but it's pretty stable nowadays, and if so we can add the new methods.

- make it dynamic

``` clojure
(def ^:dynamic *http-request-methods* #{:get :post :put :delete :options ,,,})

(s/def :ring/request-method *http-request-methods*)
```

And let people `alter-var-root` if they must. 

I would also add

``` clojure
(s/def :ring/middleware (s/fdef :args (s/cat :handler :ring/handler
                                             :options (s/* any?))
                                :ret :ring/handler))
```

**Comment by weavejester** [comment]
Neither the Ring nor the HTTP specification limit the request methods you can use, so any spec shouldn't either.

**Comment by alexanderkiel** [comment]
@plexus I'm with @weavejester and would let the request methods open. I'll change this.

Regarding `:ring/middleware`: I tried similar definitions but there is a problem using `:ring/handler` as argument spec. Spec will call all functions in order to test whether they follow the argument spec. While calling the handler, spec generates a request from `:ring/request`. That request has only the very basic keys in it. So all your handlers have to work with such a basic request. Often one assumes keyword params or such in a request because one knows that the handler will be called after `wrap-keyword-params`.

**Comment by weavejester** [comment]
Because I don't want Ring itself to require Clojure 1.9.0, I've created the [Ring-Spec](https://github.com/ring-clojure/ring-spec) project for this work.

**Comment by weavejester** [comment]
Ring-Spec 0.0.1 has been released, so I'm closing this issue.
