### ISSUE TITLE
How to scale apps that using ring on multiple servers?

### ISSUE THREAD

**Issue by ertugrulcetin** [ring-clojure/ring#290]
I'm using ring for my app and would like to learn how to run my app on multiple instances?

The reason is I have a `CSRF` token which is generated by ring, every time user does something server validates that token if I run my app on couple of servers and have one load balancer, some instances wouldn't recognise the token because it's generated per instance(session based).

Is ring going to support this? or I need to use something like `Hazelcast` and persist token into stateful map and share across all the servers?

**Comment by weavejester** [comment]
You just need to use a session store that can be distributed across servers.

If you're using the cookie session store, you need to supply a secret key that all servers share. For example:

```clojure
(wrap-session handler (cookie-store {:key (System/getenv "COOKIE_STORE_KEY")}))
```

Note that the cookie key needs to be exactly 16 bytes.

Otherwise, you can use a session store that saves your session to a common database. [The protocol](https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/session/store.clj) is straightforward, and people have created session store libraries for various databases.

**Comment by ertugrulcetin** [comment]
Thank you so much for your reply.
