### ISSUE TITLE
Is deleting a session when using cookie-store leaking too much information?

### ISSUE THREAD

**Issue by cfelde** [ring-clojure/ring#304]
Hi,

I might be missing something here as encryption isn't my primary area of expertise, but I'm wondering if there's an issue of information leakage when deleting a session (ie, setting :session nil in a response) while using the cookie-store.

Looking at the related [code](https://github.com/ring-clojure/ring/blob/57e8b576441e09515bcd7f83718e7b068ba64699/ring-core/src/ring/middleware/session/cookie.clj#L93), when deleting a session we seal an empty map.

So that means an attacker will know the content of a deleted session as it's well defined. We also include the IV as we concat it in [encrypt](https://github.com/ring-clojure/ring/blob/57e8b576441e09515bcd7f83718e7b068ba64699/ring-core/src/ring/middleware/session/cookie.clj#L45).

So the only thing an attacker wouldn't know is the secret key. Is that a risk, or am I just being paranoid? Would it not be safer to set the session cookie to an empty string on delete?

**Comment by weavejester** [comment]
The IV isn't something that's supposed to be secret; we just need to ensure that it's not reused, which is why it's created from a cryptographically secure PRNG. The rest of what you describe is called a known-plaintext attack, which AES is resistant to. Knowing the plaintext and IV does not mean we can derive the key.
