### ISSUE TITLE
Could not locate ring/middleware/multipart_params/temp_file.clj on classpath

### ISSUE THREAD

**Issue by masztal** [ring-clojure/ring#345]
When I'm creating uberjar with uberjar-exclusions *.clj, I've got en error:

> Could not locate ring/middleware/multipart_params/temp_file__init.class or ring/middleware/multipart_params/temp_file.clj on classpath

Why temp_file.clj is loading during the runtime and not at the compilation time?

[https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/multipart_params.clj#L107](https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/multipart_params.clj#L107)

**Comment by weavejester** [comment]
It's useful to supply a default multipart store, but it's also useful to avoid loading namespaces that are not required if the multipart store is explicitly specified.

**Comment by masztal** [comment]
Does loading that namespace is so much overhead?
PS: The dirty trick is:
`:uberjar-exclusions #"^(?!.*temp_file).*clj$"]`

**Comment by weavejester** [comment]
Clojure startup time is slow because of the time it takes to load namespaces, so every optimisation we can do around that is a useful one.

Aside from using `:uberjar-exclusions`, you could also just explicitly require the temp-file namespace, thereby turning it from a runtime dependency into a compile-time one.

**Comment by masztal** [comment]
Thanks for a tip :) I belive that's all.
