### ISSUE TITLE
Remove dependency on clj-time

### ISSUE THREAD

**Issue by potetm** [ring-clojure/ring#358]
Any chance we can remove the dependency on clj-time? It looks like it's only used for serializing cookie dates to seconds and rfc822. clj-time and Joda are two fairly large libraries. I think it would be worth avoiding them for the trivial functionality required.

Now that I look at it, the behavior in cookies.clj is a little wonky. It accepts some values that it requires to be of a type from a third-party lib, serializes them, but does not deserialize back to the original type.

At any rate, since Java 8 is now the minimum supported version, the functionality should be covered by the new `java.time` package.

The downside here is it would be  breaking change. I'm willing to submit a PR if you deem it a worthwhile change.

**Comment by potetm** [comment]
touche -- though it _will_ still break if users aren't explicitly pulling clj-time onto the classpath. Probably worth noting in the patch notes.

I'll take a pass at this soon.

**Comment by potetm** [comment]
Are you willing to make Java 8 the minimum for ring? If not, I can try and make it < 8 compatible.

**Comment by potetm** [comment]
Repro:

1. The user depends on ring-core, but not on clj-time.
2. The user is passing a Joda `Interval` as a `:max-age`. This works because ring-core pulls clj-time onto the classpath.
3. We remove our dependency on clj-time. We dynamically load code to handle Joda classes if they're on the classpath.
4. The user upgrades. Their code will not compile because Joda is no longer on their classpath.

The fix for them would be to explicitly add clj-time or Joda time on their classpath. Not onerous, but worth noting.

**Comment by weavejester** [comment]
So you're saying what happens if a user is using JodaTime, but hasn't put in an explicit dependency for JodaTime and is instead relying on Ring's implicit dependency?

I think it's perfectly fine to fail in that case. Ring's dependencies are not part of its API, and if someone is using a JodaTime class, or requiring clj-time in their code, then they should have an explicit dependency for it. I don't even think we need to make a note about it; if they're using a library that isn't in their direct dependencies, then that's an issue with their project.
