### ISSUE TITLE
How do I use resource-response with absolute path,here I found nothing wrong but can't handle this

### ISSUE THREAD

**Issue by Ne-Steiner** [ring-clojure/ring#399]
Here I have a file named "1.jpg" in "/home/steiner/picture/",then I use 
```clojure
(resouce-response "/home/steiner/picture/1.jpg")
```
however it returns nil  
what about :root option??
```clojure 
(resource-response "/home/steiner/picture/1.jpg" {:root "/"})
```
still nil 
also this is useless too
```clojure
(resource-response "1.jpg" {:root "/home/steiner/picture/"})
```
what's the wrong with my operation??

**Comment by weavejester** [comment]
While I don't mind answering some questions, the Ring issue tracker should mainly be reserved for issues with Ring, rather than basic usage questions. Instead, I'd recommend asking questions on the [Clojurians Slack channel](http://clojurians.net/), or the [Ring Google Group](http://groups.google.com/group/ring-clojure), or the [Clojure Google Group](http://groups.google.com/group/clojure), or [/r/clojure](https://www.reddit.com/r/Clojure/).

In your case, the problem you have is that you want to return a *file*, and not a resource. The `file-response` function is what you want. A resource exists on the Java classpath, and is typically something you'd place in the `resources` directory of your project.
