### ISSUE TITLE
ring hangs when attempting to use websockets with :async? true

### ISSUE THREAD

**Issue by hiredman** [ring-clojure/ring#499]
reported by Thierry in the clojurians slack.

https://downey.family/p/2024-03-22/jetty-test.clj.html is a little reproducer that monkey patches ring to call complete, if you remove the monkey patching it hangs.

**Comment by LouDnl** [comment]
I can confirm that implementing this monkey patch makes the async response work immediately!`

**Comment by weavejester** [comment]
Thanks for the report! I was wondering how this could have gotten past the tests, but it turns out this is an omission in the test suite; websockets are never tested with async handlers!

I'll plug the hole in the test suite and release a fix this weekend. Looks like it should just be a case of changing:

```clojure
(upgrade-to-websocket request response response-map)
```

To:

```clojure
(do (upgrade-to-websocket request response response-map)
    (.complete context))
```

**Comment by LouDnl** [comment]
Thanks in advance @weavejester
